CLASS_MAPPING = {
    "area": 0,
    "heatmap": 1,
    "bar": 2,
    "interval": 3,
    "line": 4,
    "manhattan": 5,
    "map": 6,
    "pie": 7,
    "scatter": 8,
    "scatter-line": 9,
    "surface": 10,
    "venn": 11,
    "box": 12,
}